issuer: http://dex:5556/dex
storage:
  type: memory
web:
  http: 0.0.0.0:5556

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: my-app
    redirectURIs:
      - 'http://localhost:3000/'
    name: 'My Test App'
    secret: my-secret

enablePasswordDB: true
staticPasswords:
  - email: "test@example.com"
    hash: "$2y$10$JcmlXnV1y7.egUdKwYNbseOnqYVIGc323gtvvHh4ZuSPZB30veYZy"
    username: "test"
    userID: "1234"
