name: Run tests
on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'

jobs:
  test-runner:
    runs-on: ubuntu-latest
    container: node:18

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: yarn install
        run: |
          yarn install
      - name: Integration tests
        run: |
          cd integration-tests
          yarn test:ci
#          yarn wait:ci
      - name: Filter parser tests
        if: always()
        run: |
          cd packages/filterparser
          yarn test:ci
      - name: Datalib (perspective) tests
        if: always()
        run: |
          cd packages/datalib
          yarn test:ci
      - uses: tanmen/jest-reporter@v1
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-file: integration-tests/result.json
          action-name: Integration tests
      - uses: tanmen/jest-reporter@v1
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-file: packages/filterparser/result.json
          action-name: Filter parser test results
      - uses: tanmen/jest-reporter@v1
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-file: packages/datalib/result.json
          action-name: Datalib (perspectives) test results

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: Pwd2020Db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: mysql:8.0.18
        env:
          MYSQL_ROOT_PASSWORD: Pwd2020Db

      mssql:
        image: mcr.microsoft.com/mssql/server
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Pwd2020Db
          MSSQL_PID: Express

      clickhouse:
        image: bitnami/clickhouse:24.8.4
        env:
          CLICKHOUSE_ADMIN_PASSWORD: Pwd2020Db

      # cockroachdb:
      #   image: cockroachdb/cockroach
